[package]
name = "basic"
version = "0.1.0"
edition = "2018"

[dependencies]
lambda_runtime = "0.4.1"
tokio = { version = "1.0", features = ["macros", "io-util", "sync", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
simple_logger = "1.6.0"
log = "^0.4"